import { Clock3, MapPin, Phone } from "lucide-react";
import type { FulfillmentOptions, Locale, PaymentMethod, StoreConfig } from "@/lib/api/contracts";
import { localizedField } from "@/lib/i18n/fields";
import { Alert } from "@/components/ui/alert";

export type InfoSlug = "about" | "contact" | "privacy" | "terms" | "returns" | "shipping" | "payment";

export function InfoPage({ slug, locale, config, fulfillment, paymentMethods }: { slug: InfoSlug; locale: Locale; config: StoreConfig | null; fulfillment: FulfillmentOptions | null; paymentMethods: PaymentMethod[] }) {
  const settings = config?.storeSettings;
  const title = titles[slug][locale];
  if (slug === "about") return <Shell title={title}><p className="max-w-3xl whitespace-pre-wrap text-lg leading-9 text-muted">{settings ? localizedField({ ar: settings.descriptionAr, en: settings.descriptionEn, generic: settings.description }, locale) || (locale === "ar" ? "النجوم تيليكوم متجر تقنية عربي أولًا يعتمد على بيانات المتجر المباشرة." : "Alnjoom Telecom is an Arabic-first technology store driven by live store data.") : locale === "ar" ? "تعذّر تحميل وصف المتجر حاليًا." : "The store description is currently unavailable."}</p></Shell>;
  if (slug === "contact") return <Shell title={title}>{settings ? <div className="grid gap-4 sm:grid-cols-2"><Card icon={Phone} label={locale === "ar" ? "الهاتف" : "Phone"} value={settings.phone} /><Card icon={MapPin} label={locale === "ar" ? "العنوان" : "Address"} value={[settings.address, settings.city, settings.country].filter(Boolean).join("، ")} /><div className="surface-card p-5 sm:col-span-2"><h2 className="mb-3 flex items-center gap-2 font-bold"><Clock3 className="size-5 text-brand" />{locale === "ar" ? "ساعات العمل" : "Working hours"}</h2>{settings.workingHours.length ? <ul className="grid gap-2 sm:grid-cols-2">{settings.workingHours.map((day) => <li key={day.day} className="flex justify-between gap-3 rounded-lg bg-surface p-3 text-sm"><strong>{day.day}</strong><span>{day.isClosed ? locale === "ar" ? "مغلق" : "Closed" : day.slots.map((slot) => `${slot.open}–${slot.close}`).join("، ")}</span></li>)}</ul> : <p className="text-muted">{locale === "ar" ? "لم تُضبط الساعات." : "Hours are not configured."}</p>}</div></div> : <Alert tone="error">{locale === "ar" ? "بيانات التواصل غير متاحة من إعدادات المتجر." : "Contact data is unavailable from store configuration."}</Alert>}</Shell>;
  if (slug === "shipping") return <Shell title={title}>{fulfillment?.hasOptions ? <div className="grid gap-3 sm:grid-cols-2">{fulfillment.pickup.map((method) => <MethodCard key={method.id} title={method.displayName} description={method.description} />)}{fulfillment.deliveryZones.flatMap((zone) => zone.methods.map((method) => <MethodCard key={method.id} title={method.displayName} description={[zone.name, method.description].filter(Boolean).join(" — ")} />))}</div> : <Alert>{locale === "ar" ? "لا توجد خيارات شحن أو استلام منشورة حاليًا." : "No fulfillment options are currently published."}</Alert>}</Shell>;
  if (slug === "payment") return <Shell title={title}>{paymentMethods.length ? <div className="grid gap-3 sm:grid-cols-2">{paymentMethods.map((method) => <MethodCard key={method.id} title={localizedField({ ar: method.nameAr, en: method.nameEn, generic: method.name }, locale)} description={localizedField({ ar: method.descriptionAr, en: method.descriptionEn, generic: method.description }, locale)} />)}</div> : <Alert>{locale === "ar" ? "لا توجد طرق دفع منشورة حاليًا." : "No payment methods are currently published."}</Alert>}</Shell>;
  return <Shell title={title}><Alert>{locale === "ar" ? "لم يزوّد المشروع بنص قانوني معتمد لهذه الصفحة بعد. لن نعرض محتوى قانونيًا مولّدًا أو قديمًا، والصفحة مستبعدة من الفهرسة حتى الاعتماد." : "Approved legal copy has not been supplied. Generated or stale legal text is not shown, and this page remains excluded from indexing until approval."}</Alert></Shell>;
}

function Shell({ title, children }: { title: string; children: React.ReactNode }) { return <main id="main-content" className="container-shell section-space"><h1 className="mb-7 text-3xl font-black sm:text-4xl">{title}</h1>{children}</main>; }
function Card({ icon: Icon, label, value }: { icon: typeof Phone; label: string; value: string | null }) { return <div className="surface-card p-5"><Icon className="mb-3 size-6 text-brand" /><strong>{label}</strong><p className="mt-2 leading-7 text-muted">{value || "—"}</p></div>; }
function MethodCard({ title, description }: { title: string; description: string | null }) { return <article className="surface-card p-5"><h2 className="font-bold">{title}</h2>{description ? <p className="mt-2 text-sm leading-7 text-muted">{description}</p> : null}</article>; }
const titles: Record<InfoSlug, Record<Locale, string>> = { about: { ar: "عن النجوم تيليكوم", en: "About Alnjoom Telecom" }, contact: { ar: "تواصل معنا", en: "Contact us" }, privacy: { ar: "سياسة الخصوصية", en: "Privacy policy" }, terms: { ar: "الشروط والأحكام", en: "Terms and conditions" }, returns: { ar: "الاستبدال والاسترجاع", en: "Returns" }, shipping: { ar: "خيارات الشحن والاستلام", en: "Shipping and pickup" }, payment: { ar: "طرق الدفع", en: "Payment methods" } };
